SELECT * FROM HR.departments;
SELECT * FROM HR.employees;

-- OVER PARTITION BY COZUMU---

SELECT DISTINCT d.DEPARTMENT_NAME, SUM(e.SALARY) OVER(PARTITION BY d.DEPARTMENT_NAME) AS "Total salary"  
FROM HR.DEPARTMENTS d JOIN HR.EMPLOYEES e ON(d.DEPARTMENT_ID=e.DEPARTMENT_ID);


--- GROUP BY COZUMU ---

SELECT d.DEPARTMENT_NAME, SUM(e.SALARY)AS "Total salary"  
FROM HR.DEPARTMENTS d JOIN HR.EMPLOYEES e ON(d.DEPARTMENT_ID=e.DEPARTMENT_ID)
GROUP BY (d.DEPARTMENT_NAME);

